steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO/$_BACKEND', './backend']
  id: 'Build backend'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$LOCATION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO/$_BACKEND']
  id: 'Push backend'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO/$_FRONTEND', './frontend']
  id: 'Build Frontend'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$LOCATION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO/$_FRONTEND']
  id: 'Push Frontend'

# - name: 'gcr.io/cloud.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'gcloud'
#   id: 'Deploy to K8'
#   args: ['deploy', 'apply', '--file', 'deploy/pipeline.yaml', '--region', 'us-east4',
#         'deploy', 'releases', 'create', 'app1-release-${SHORT_SHA}', '--deliver', 'test-cd-pipeline', '--region', 'us-east4', '--from-k8s-manifest', 'k8/app.yaml']

- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud deploy apply --file deploy/pipeline.yaml --region us-east4
    gcloud deploy apply --file deploy/dev.yaml --region us-east4

    gcloud deploy releases create 'app1-release-${SHORT_SHA}' --delivery-pipeline test-cd-pipeline --region us-east4 --from-k8s-manifest=./kubernetes/app.yaml

#--from-k8s-manifest=kubernetes/app.yaml
#--images ubuntu1=gcr.io/us-east4-docker.pkg.dev/us-gcp-ame-adv-9504d-npd-1/test-artifact/ubuntu

options:
  logging: CLOUD_LOGGING_ONLY
