apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-pipeline
  annotations:
    target: apis
description: testing prod pipeline
requireApproval: true
executionConfigs:
- executionTimeout: 10800s
  # serviceAccount: us-adv-devops-sa@us-gcp-ame-adv-56cad-prd-1.iam.gserviceaccount.com
gke:
  cluster: projects/us-gcp-ame-adv-56cad-prd-1/locations/us-east4/clusters/test-prod
  dnsEndpoint: true