apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    target: apis
  labels:
    app: backend
  name: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: ubuntu-backend
        image: ubuntu-backend